Correct FRUID retrieving algorithm for AST2600_MNGR
Change-Id: I3bf7d586c8c77706475aeef6bbbf13c09ecd51ac

diff --git a/meta-mcst/meta-common/recipes-mcst/net-initial/files/set_mac b/meta-mcst/meta-common/recipes-mcst/net-initial/files/set_mac
--- a/meta-mcst/meta-common/recipes-mcst/net-initial/files/set_mac
+++ b/meta-mcst/meta-common/recipes-mcst/net-initial/files/set_mac
@@ -9,32 +9,61 @@ bmc_addr_base=0x1E
 env_eth0addr=`fw_printenv ethaddr 2>/dev/null | sed 's/^ethaddr=//' | tr '[:lower:]' '[:upper:]'`
 env_eth1addr=`fw_printenv eth1addr 2>/dev/null | sed 's/^eth1addr=//' | tr '[:lower:]' '[:upper:]'`
 
-if [ -f /var/volatile/motherboard_info.xml ]
-then
-    fru_ethaddr_base=`xml sel -t -v '/fruinfo/internal_use_area/mac_addr' /var/volatile/motherboard_info.xml 2>/dev/null | sed 's/ //g;s/,//g;s/0x//g'`
-else
-    if [ -z "$env_eth0addr" -o -z "$env_eth1addr" ]
-    then
-        echo "Note: Board has no valid FRU ID in EEPROM, and no MAC address in environment; using default MAC address. " 1>&2
-        fru_ethaddr_base=""
-    else
-        echo "Note: Board has no valid FRU ID in EEPROM, but has MAC address in environment; using the one from environment. " 1>&2
-        exit 0
-    fi
-fi
+[ -f /etc/reimu_fruid.conf ] && . /etc/reimu_fruid.conf
 
-if echo $fru_ethaddr_base | grep -q '^98A7B0'
-then
-    set_eth0addr=`printf %X $((0x$fru_ethaddr_base + $bmc_addr_base))`
-    set_eth1addr=`printf %X $((0x$fru_ethaddr_base + $bmc_addr_base + 1))`
-    split_mac() { echo ${1:0:2}:${1:2:2}:${1:4:2}:${1:6:2}:${1:8:2}:${1:10:2}; }
-    set_eth0addr=`split_mac $set_eth0addr`
-    set_eth1addr=`split_mac $set_eth1addr`
-else
-    echo "Warning: Board has no valid MAC address in FRU ID, using default MAC address. " 1>&2
-    set_eth0addr=$default_eth0addr
-    set_eth1addr=$default_eth1addr
-fi
+set_eth0addr=$default_eth0addr
+set_eth1addr=$default_eth1addr
+
+split_mac() { echo ${1:0:2}:${1:2:2}:${1:4:2}:${1:6:2}:${1:8:2}:${1:10:2}; }
+
+convert_mac()
+{
+    if [ -f $1 ]
+    then
+        fru_ethaddr_base=`xml sel -t -v '/fruinfo/internal_use_area/mac_addr' /var/volatile/motherboard_info.xml 2>/dev/null | sed 's/ //g;s/,//g;s/0x//g'`
+    else
+        if [ -z "$env_eth0addr" -o -z "$env_eth1addr" ]
+        then
+            echo "Note: $3 has no valid FRU ID in EEPROM, and no MAC address in environment; using default MAC address." 1>&2
+            fru_ethaddr_base=""
+        else
+            echo "Note: $3 has no valid FRU ID in EEPROM, but has MAC address in environment; using the one from environment." 1>&2
+            exit 0
+        fi
+    fi
+
+    if echo $fru_ethaddr_base | grep -q '^98A7B0'
+    then
+        set_eth0addr=`printf %X $((0x$fru_ethaddr_base + $2))`
+        set_eth1addr=`printf %X $((0x$fru_ethaddr_base + $2 + 1))`
+        set_eth0addr=`split_mac $set_eth0addr`
+        set_eth1addr=`split_mac $set_eth1addr`
+    else
+        echo "Warning: $3 has no valid MAC address in FRU ID, using default MAC address." 1>&2
+    fi
+}
+
+read_from_platform()
+{
+    convert_mac /var/volatile/motherboard_info.xml $bmc_addr_base Motherboard
+}
+
+read_from_module()
+{
+    if /usr/sbin/get-fruid 4 0x57 /var/volatile/bmc_info.xml
+    then
+        convert_mac /var/volatile/bmc_info.xml 0 BMC
+    else
+        echo "Can't read BMC FRU ID EEPROM; using default MAC address." 1>&2
+    fi
+}
+
+case "$FRUID_SOURCE" in
+    module)
+        read_from_module;;
+    *)
+        read_from_platform;;
+esac
 
 if [ "$env_eth0addr" == "$set_eth0addr" -a "$env_eth1addr" == "$set_eth1addr" ]
 then
